name: ~
description: ~
brand-icon: ~
brand-title: ~

plugins:
  - jekyll-github-metadata
  - jekyll-navigation

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
