name: ~
description: ~
brand-icon: ~
brand-name: ~
include:
  - README.md

plugins:
  - jekyll-github-metadata

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

source: ./docs
baseurl: ""
