name: ~
description: ~
favicon: ~
brand: ~

destination: ./.site
include:
  - README.md

plugins:
  - jekyll-github-metadata

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
