name: ~
name_: "Jekyll Plain Theme"
description: ~
description_: "Jekyll Plain Theme is a simple and clean theme for Jekyll."
brand: ~
brand_: <img class="icon" src="/assets/image/brand-icon.svg"/>Jekyll Plain
favicon: ~
favicon_: /assets/image/brand-icon.svg

destination: ./.site
include:
  - README.md

plugins:
  - jekyll-github-metadata

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
