name: "Jekyll true minimal theme"
description: "Lightweight theme"
brand: <img class="icon" src="/static/image/brand-icon.svg"/>Jekyll Plain

source: .
destination: ./_site

include:
  - README.md
  - static/image/brand-icon.svg

plugins:
  - jekyll-github-metadata

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
